[package]
name = "ticker-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
cosmos-grpc-client = "3.0.1"
env_logger = "0.11.3"
log = "0.4.21"
orion = "0.17.6"
rpassword = "7.3.1"
serde = "1.0.203"
serde_json = "1.0.117"
slack-hook = "0.8.0"
tokio = "1.38.0"
toml = "0.8.14"
