[[contract]]
type = "stride_liquid_staker"
chain_prefix = "neutron"
address = "neutron12awcg84h2r90gh0aqpn66gl2qrlwdyweqjkuptg5zlfmrm668exslnxnyt"

[[contract]]
type = "ibc_forwarder"
chain_prefix = "neutron"
address = "neutron1slxdtn39qgeukc4kmfuxlhz5thwed2ffawl76jfhh95wavns8jgq3tspa0"

[[contract]]
type = "ibc_forwarder"
chain_prefix = "neutron"
address = "neutron155r0uy35rurc7n9844352r4eynvd5v2e06x3lnsyzzw4cdzam7vs50yefq"

[[contract]]
type = "astroport_liquid_pooler"
chain_prefix = "neutron"
address = "neutron1lvv27zlz3df88wqmk72fyw5dc8qjzgx6njmrsj6tczxvyul44gaqlj6f3s"

[[contract]]
type = "remote_chain_splitter"
chain_prefix = "neutron"
address = "neutron1ae09hqakgfldu0vesa3mtutadqq6mnqlpeuy95dqqy25wzrv620qemzfyp"

[[contract]]
type = "interchain_router"
chain_prefix = "neutron"
address = "neutron1gagpgagegcksjqjgx3an35hpfgeqje8cjvdfx67ld55t3pwq5h8sk2dc05"

[[chain]]
chain_prefix = "neutron"
base_denom = "untrn"
endpoint = "https://0.0.0.0:37425"
