[[contract]]
type = "stride_liquid_staker"
chain_prefix = "neutron"
address = "neutron1kklrhxe95077y380gvsa0f8nkm2ksye444dtmeq7tvtnydtv0umsa6e9ec"

[[contract]]
type = "ibc_forwarder"
chain_prefix = "neutron"
address = "neutron1hglusfulepxanhchuqa0m6cptauldsdkwml7h53msz60khnvx0sq2y34cm"

[[contract]]
type = "ibc_forwarder"
chain_prefix = "neutron"
address = "neutron1w06mc6ltfzfh9vj65t4fa49tnexj42vqhadwqwyqk3kzuculmcmqdvm8qh"

[[contract]]
type = "astroport_liquid_pooler"
chain_prefix = "neutron"
address = "neutron1zh946xg0ra7xn7nxvydgtgmw3zcndqlwt0rsf9y4v9vldw6jzgsqt7fzlg"

[[contract]]
type = "remote_chain_splitter"
chain_prefix = "neutron"
address = "neutron1wtj5qu97tk4jp6cmcd4qt776ymn3ql4ct7hwsm4p52yg9zpxf6nquhkndn"

[[contract]]
type = "interchain_router"
chain_prefix = "neutron"
address = "neutron19ypnaexra8hspren0gagtz2r00ym57t93e27kuwckyysys0h376qedrh9l"

[[chain]]
chain_prefix = "neutron"
base_denom = "untrn"
endpoint = "https://0.0.0.0:41781"
